owner: Hans5958
repo: Scratch-Upptime

sites:
  - name: Main website
    url: https://scratch.mit.edu
  - name: Main API
    url: https://api.scratch.mit.edu
  - name: Download server 1
    url: https://download.scratch.mit.edu
  - name: Download server 2
    url: https://downloads.scratch.mit.edu/desktop/Scratch%20Setup.exe # Installer for Windows
  - name: CDN server 1
    url: https://cdn.scratch.mit.edu/scratchr2/static/__867ec47c1657f9fde21932c086a84195__/images/logo_sm.png # Small scratch logo
  - name: CDN server 2
    url: https://cdn2.scratch.mit.edu/get_image/user/1882674_48x48.png # griffpatch profile picture
  - name: Project JSON server
    url: https://projects.scratch.mit.edu
  - name: Assets server
    url: https://assets.scratch.mit.edu
  - name: Uploads server
    url: https://uploads.scratch.mit.edu/projects/thumbnails/10128407.png # Paper Minecraft
  - name: Cloud Data API
    url: https://clouddata.scratch.mit.edu
    expectedStatusCodes:
      - 101
      - 404 # TODO: Hope there is another way...
  - name: Backpack API
    url: https://backpack.scratch.mit.edu
  - name: Synthesis service
    url: https://synthesis-service.scratch.mit.edu
  - name: Translation service
    url: https://translate-service.scratch.mit.edu

status-website:
  name: Scratch Upptime (unofficial)
  cname: scratch-upptime.netlify.app
  introTitle: Welcome to **[Scratch](https://scratch.mit.edu)**'s (unofficial) Upptime status page.
  introMessage: This is the status page for known services related to [Scratch](https://scratch.mit.edu). It monitors them for free using GitHub services, thanks to [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: Auto5958
commitMessages:
  commitAuthorName: Auto5958
  commitAuthorEmail: 69833949+Auto5958@users.noreply.github.com
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
